[package]
name = "cypress1/wasix-echo-server"
version = "0.1.0"
description = "Echo server"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wasmerio/edge"
wasmer-extra-flags = "--enable-threads --net --enable-bulk-memory"

[[module]]
name = "wasix-echo-server"
source = "wasix-echo-server.wasm"
abi = "wasi"

[[command]]
name = "wasix-echo-server"
module = "wasix-echo-server"
runner = "https://webc.org/runner/wasi"
